# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Newsletter

# Model Form Field configuration
form: $/dmrch/contact/models/newsletter/fields.yaml

# Model Class name
modelClass: Dmrch\Contact\Models\Newsletter

# Default redirect location
defaultRedirect: dmrch/contact/newsletter

# Create page
create:
    title: Create Newsletter
    redirect: dmrch/contact/newsletter/update/:id
    redirectClose: dmrch/contact/newsletter

# Update page
update:
    title: Edit Newsletter
    redirect: dmrch/contact/newsletter
    redirectClose: dmrch/contact/newsletter

# Preview page
preview:
    title: Preview Newsletter
